### ISSUE TITLE
Improve testing / debugging

### ISSUE THREAD

**Issue by StephanAkkerman** [StephanAkkerman/fintwit-bot#579]
Now the whole thing needs to be ran including all the cogs, there should be better methods
Maybe add to the config an option to run only specific cogs like

```yaml
DEBUG_MODE: True

DEBUG_COGS:
  - timeline
  - rsi_heatmap
  - etc.
```
