### ISSUE TITLE
The bot always created new channels when restarted, instead of having persistent channels and grabbing their IDs

### ISSUE THREAD

**Issue by TheJoshue** [StephanAkkerman/fintwit-bot#691]
So when i restart the bot it creates again all the channels enabled in config.yaml

**Comment by TheJoshue** [comment]
This is my docker log:
https://mclo.gs/XzNB4dm

This is my Dockerfile:
```
FROM python:3.11.11

WORKDIR /bot

COPY requirements.txt /bot/

RUN pip install -r requirements.txt

COPY . /bot/

CMD ["python", "src/main.py"]
```

This is my `docker-compose.yml`:
```yml
services:

  bot-1:
    image: discordbot-fintwit:1.4.5
    container_name: discordbot-fintwit-bot-1
    restart: always

    environment:
      # Discord Bot
      DISCORD_TOKEN: "<MY_BOT_TOKEN>"
      DISCORD_GUILD: "<MY_GUILD_ID>"

      # REDDIT API
      REDDIT_USERNAME: ""
      REDDIT_PASSWORD: ""
      REDDIT_APP_NAME: ""
      REDDIT_PERSONAL_USE: ""
      REDDIT_SECRET: ""

    volumes:
      - /home/bot-5/configs/config.yaml:/bot/config.yaml
      - /home/bot-5/configs/curl.txt:/bot/curl.txt
```

In curl i have added `HomeTimeline` variable cURL (bash) even though later it showed also HomeLatestTimeline too, but i did not change it, and both of this were from "For You" and not "Following" page because on "Following" it does not show that variable

Any ideas? @StephanAkkerman thank you in advance
